services:
  app:
    container_name: app_email
    build: ./
    command: bash -c "poetry run src/manage.py migrate && poetry run src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src/attachments/:/app/src/attachments/
    networks:
      - email_net

  db:
    image: postgres:15
    container_name: db_email
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    networks:
      - email_net

networks:
  email_net:
    name: email_net
    external: true
